In [1]:
import numpy as np

In [2]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [3]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [4]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [5]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[ 1.00000000e+00 -4.44089210e-16 -1.11022302e-16]
 [ 4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 4.44089210e-16  8.88178420e-16  1.00000000e+00]] 1
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
check OK


In [6]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [7]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [8]:
# обратная матрица - вырожденный случай
np.linalg.inv(A2)

LinAlgError: Singular matrix

In [9]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [11]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

A3 inversed:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [12]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

A3 @ A3 inversed = E check:
 [[ 0.  1.  0.]
 [ 0.  2.  0.]
 [-4.  3.  2.]]
check failed


In [13]:
print('det(A1)):\n',np.linalg.det(A1))

det(A1)):
 -3.000000000000001


In [14]:
print('det(A2)):\n',np.linalg.det(A2))

det(A2)):
 0.0


In [15]:
print('det(A3)):\n',np.linalg.det(A3))

det(A3)):
 -9.51619735392994e-16


In [16]:
# обратная матрица - неустойчивость
A4=np.array([[1,2,3],[4,5,6],[1,2,3.00005]])
print('A4:\n',A4)
print('rk(A4):\n',np.linalg.matrix_rank(A4))
print('det(A4):\n',np.linalg.det(A4))
print('A4 inverse:\n',np.linalg.inv(A4))

A4:
 [[1.      2.      3.     ]
 [4.      5.      6.     ]
 [1.      2.      3.00005]]
rk(A4):
 3
det(A4):
 -0.00014999999999965044
A4 inverse:
 [[-2.00016667e+04  6.66666667e-01  2.00000000e+04]
 [ 4.00013333e+04 -3.33333333e-01 -4.00000000e+04]
 [-2.00000000e+04  0.00000000e+00  2.00000000e+04]]


In [17]:
# обратная матрица - неустойчивость вблизи нулевого определителя
A5=np.array([[1,2,3],[4,5,6],[1,2,3.00000005]])
print('A5:\n',A5)
print('rk(A5):\n',np.linalg.matrix_rank(A5))
print('det(A5):\n',np.linalg.det(A5))
print('A5 inverse:\n',np.linalg.inv(A5))

A5:
 [[1.         2.         3.        ]
 [4.         5.         6.        ]
 [1.         2.         3.00000005]]
rk(A5):
 3
det(A5):
 -1.5000000042064706e-07
A5 inverse:
 [[-2.00000016e+07  6.66666667e-01  1.99999999e+07]
 [ 4.00000012e+07 -3.33333333e-01 -3.99999999e+07]
 [-1.99999999e+07  0.00000000e+00  1.99999999e+07]]


In [18]:
# обратимость матрицы Грама линейно независимой системы векторов
v1=np.array([1,2,1])
v2=np.array([1,1,1])
A=np.array([v1,v2]).T
print('A:\n',A)
print('Матрица Грама:\n',A.T@A)

A:
 [[1 1]
 [2 1]
 [1 1]]
Матрица Грама:
 [[6 4]
 [4 3]]


In [19]:
print('Ранг матрицы Грама:\n',np.linalg.matrix_rank(A.T@A))

Ранг матрицы Грама:
 2


In [20]:
print('Определитель матрицы Грама:\n',np.linalg.det(A.T@A))

Определитель матрицы Грама:
 2.0000000000000004


In [21]:
print('Обратная к матрице Грама:\n',np.linalg.inv(A.T@A))

Обратная к матрице Грама:
 [[ 1.5 -2. ]
 [-2.   3. ]]


# Самостоятельная работа

In [24]:
#Дана матрица A:

A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
#Найдите матрицу, обратную матрице A.

#В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

np.linalg.inv(A)[1,0]
#0.375

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [25]:
#Дана система векторов:

v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [30]:
#Найдите ранг системы векторов v1, v2, v3, v4. Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.
S = np.array([v1,v2,v3,v4]).T
np.linalg.matrix_rank(S)
#4

4

In [32]:
#Найдите матрицу Грама системы векторов v1, v2, v3, v4: G=At@A. В качестве ответа запишите элемент из четвёртого столбца первой строки.
G=S.T@S
G[0,3]

-35

In [34]:
#Найдите определитель матрицы Грама G системы v1, v2, v3, v4. Ответ округлите до целого числа.
round(np.linalg.det(G))
#3716648

3716648

In [35]:
#Найдите обратную матрицу к матрице Грама G системы v1, v2, v3, v4. 
# В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.
round(np.linalg.inv(G)[2,0],3)
#-0.026

-0.026

In [2]:
np.linalg.inv(np.array([[1,2],[3,7]]))

array([[ 7., -2.],
       [-3.,  1.]])

In [3]:
s=np.array([[2,10,-2],[3,2,-2],[8,14,-6]]).T
np.linalg.matrix_rank(s)

2

In [5]:
s=np.array([[4,7,-1],[-4,2,5],[0,9,4]]).T
print(np.linalg.matrix_rank(s))
s_wide=np.array([[4,7,-1,7],[-4,2,5,3],[0,9,4,10]]).T
print(np.linalg.matrix_rank(s_wide))

2
2


In [18]:
s=np.array([[1,2],[-3,1],[1,2],[1,-1]])
s_t=s.T
s_t@s
f=np.linalg.inv(s_t@s)
b = np.array([1,4,5,0])
g=s_t@b
g
f@g

array([-0.5,  1.6])

In [3]:
x_1 = np.array([5, 1, 2])
x_2 = np.array([4, 2, 8])
np.corrcoef(x_1, x_2)

array([[1.        , 0.05241424],
       [0.05241424, 1.        ]])

In [2]:
import pandas as pd

In [26]:
#x_1 = pd.DataFrame([[5.1,1.8,2.1,10.3,12.1,12.6],[10.2,3.7,4.1,20.5,24.2,24.1],[10.2,3.7,4.1,20.5,24.2,24.1]])
#x_2 = np.array([10.2,3.7,4.1,20.5,24.2,24.1])
#x_3 = np.array([2.5,0.9,1.1,5.1,6.1,6.3])
x_1 = np.array([[5.1,1.8,2.1,10.3,12.1,12.6],[10.2,3.7,4.1,20.5,24.2,24.1],[2.5,0.9,1.1,5.1,6.1,6.3]]).T

x_1 = pd.DataFrame(x_1)
x_1 = np.array(x_1.corr())
print(np.linalg.matrix_rank(x_1))
print(round(np.linalg.det(x_1),7))

3
5e-07


In [5]:
#поиск коэффициентов полиномиальной регрессии методом LOS
A = np.array([
    [1, 3, -2, 9]
]).T
y = np.array([3, 7, -5, 21])

from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=True) #вторая степень полинома, включаем столбец из единиц
X_poly = poly.fit_transform(A)
w_hat = np.linalg.inv(X_poly.T@X_poly)@X_poly.T@y
y_pred = X_poly @ w_hat

print(w_hat)
## [ 0.11446013  2.46095638 -0.01608801]

[ 0.11446013  2.46095638 -0.01608801]


Вычислите коэффициенты линейной регрессии с L2-регуляризацией, используя аналитическую формулу Тихонова, если:
    
Коэффициент регуляризации alfa=1.

В качестве ответа приведите значения полученных коэффициентов линейной регрессии, округлив их до второго знака после точки-разделителя.

In [6]:
from sklearn.linear_model import Ridge

# матрица наблюдений (включая столбец единиц)
A = np.array([
    [1, 1, 1, 1, 1],
    [5, 9, 4, 3, 5],
    [15, 18, 18, 19, 19],
    [7, 6, 7, 7, 7]
]).T
# вектор целевого признака
y = np.array([24, 22, 35, 33, 36])
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
ridge = Ridge(alpha=1, fit_intercept=False)
ridge.fit(A, y)
print(f'w0 - {round(ridge.coef_[0],2)}, w1 - {round(ridge.coef_[1],2)}, w2 - {round(ridge.coef_[2],2)}, w3 - {round(ridge.coef_[3],2)}') 
## w0 - -0.09, w1 - -1.71, w2 - 1.91, w3 - 0.73

w0 - -0.09, w1 - -1.71, w2 - 1.91, w3 - 0.73


In [9]:
#Найдите собственные числа для матрицы:
#Каждое из собственных чисел округлите до целого.

# создаем матрицу А
A = np.array([
    [1, 3, 5],
    [4, -4, 9],
    [13, 7, 12]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A)
print('Собственные числа: \n', np.round(eig_values))
print('Собственные векторы: \n', eig_vectors)
#[20. -4. -7.]

Собственные числа: 
 [20. -4. -7.]
Собственные векторы: 
 [[-0.59065136 -0.9084069  -0.40394124]
 [-0.29844178 -0.16657961 -0.77823322]
 [-0.74970893  0.38346857  0.48081652]]


In [10]:
#Найдите собственные числа матрицы Грама A.T@A, если дана A
# создаем матрицу А
A = np.array([
    [1, 9, 4],
    [9, 4, 7],
    [4, 7, 12]
]).T
# вычисляем собственные числа и собственные векторы
eig_values, eig_vectors = np.linalg.eig(A.T@A)
print('Собственные числа: \n', np.round(eig_values))
print('Собственные векторы: \n', eig_vectors)

Собственные числа: 
 [391.  46.  16.]
Собственные векторы: 
 [[-0.41955589 -0.7323045  -0.5363795 ]
 [-0.55709648  0.67425896 -0.48478693]
 [-0.71667034 -0.09541992  0.69085358]]


In [15]:
#PCA
#Выберите одну главную компоненту для дальнейшего анализа. Вычислите её значения.

#Введите компоненты с округлением до второго знака после запятой.

import numpy as np
x1 = np.array([1, 2, 1, 1]).T
x2 = np.array([70, 130, 65, 60]).T

C = np.array([
[1, 0.9922],
[0.9922, 1],
])

eig_values, eig_vectors = np.linalg.eig(C)

x1_norm = (x1 - x1.mean()) / np.linalg.norm(x1)
x2_norm = (x2 - x2.mean()) / np.linalg.norm(x2)

x_new = x1_norm * eig_vectors[0][0] + x2_norm * eig_vectors[1][0]

x_new_norm = (x_new - x_new.mean()) / np.linalg.norm(x_new)

print(np.round(x_new_norm, 2))

## [-0.24  0.86 -0.29 -0.33]

[-0.24  0.86 -0.29 -0.33]
