In [3]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[10,  7,  8],
       [10,  9, 11],
       [ 7,  7,  5]])

In [4]:
B

array([[ 0, -2,  3],
       [ 3,  1, -2],
       [-2, -1, -1]])

In [5]:
# Поэлементное умножение
A*B

array([[  0, -14,  24],
       [ 30,   9, -22],
       [-14,  -7,  -5]])

In [7]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[  5 -21   8]
 [  5 -22   1]
 [ 11 -12   2]]


In [8]:
# Матричное умножение
np.dot(A,B)

array([[  5, -21,   8],
       [  5, -22,   1],
       [ 11, -12,   2]])

In [9]:
# Матричное умножение
A@B

array([[  5, -21,   8],
       [  5, -22,   1],
       [ 11, -12,   2]])

In [10]:
# Порядок умножения AB != BA
B@A

array([[  1,   3,  -7],
       [ 26,  16,  25],
       [-37, -30, -32]])

In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 8  8 10  8  6]
 [ 7  7 10 11  7]
 [ 6 10  6  7  5]]
B:
 [[ 0  3]
 [ 0  1]
 [ 2 -1]
 [ 0  1]
 [-1 -2]]


In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[14, 18],
       [13, 15],
       [ 7, 19]])

In [13]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [14]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [15]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-2  0  0  1]
 [-2 -1 -4 -2]
 [ 2  2  1  2]
 [-3  1  2  2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-2  0  0 -1]
 [-2 -2  0  2]
 [ 2  4  0 -2]
 [-3  2  0 -2]]
DA:
 [[-2  0  0  1]
 [-4 -2 -8 -4]
 [ 0  0  0  0]
 [ 3 -1 -2 -2]]


In [16]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [17]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [18]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [19]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [20]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [22]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [23]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

# Самостоятельная работа

In [27]:
#Даны матрица A и вектор х:

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
#Найдите произведение матрицы A и вектора х в том порядке, в котором их можно умножить.

#В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1.

A@x
#array([26, 30])

array([26, 30])

In [34]:
#Даны две матрицы:

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
#Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

#В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.
C=B@A
C[0,3]
#14

14

In [37]:
#Дана система векторов:

x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
#Составьте матрицу A, расположив векторы x, y, z в строках. Найдите матрицу Грама G (матрицу скалярных произведений столбцов матрицы A ) системы векторов x, y, z.

#Чему равна полученная матрица Грама ?


A=np.array([x,y,z])
G=A.T@A
G

#array([[ 6,  3,  0,  2,  4],
#       [ 3,  6,  0,  1,  8],
#       [ 0,  0,  3, -1,  4],
#      [ 2,  1, -1,  1,  0],
#      [ 4,  8,  4,  0, 16]])

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [38]:
#УСЛОВИЕ ДЛЯ ЗАДАНИЙ 7.4 И 7.5

#В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

#Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

#В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
#В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [40]:
#Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят салону определённую комиссию.

#Вектор комиссий: 

com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

#Выберите координаты вектора прибыли салона

count = np.array(Count_DF)
price = np.array(Price_DF)

revenue = count*price
profit = revenue@com
profit

#array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [52]:
#Найдите вектор прибыли стилистов.

#Выберите координаты полученного вектора:

com_for_stylist = np.ones(5)-com

profit_for_stylist = revenue@com_for_stylist
profit_for_stylist

#array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [6]:
#обратная матрица

A = np.matrix('1,2; 2,5')
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

In [7]:
# определитель матрицы

A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))

-3.000000000000001


In [8]:
A = np.matrix ("2, 0, 0; 0, 1, 0 ; 0, 0, 4")
print(np.linalg.det(A))

7.999999999999998
